name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  push:
    branches: [main]

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm ci

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.3.0

      - name: Report tool versions
        run: |
          aftman -V
          aftman list
          node -v
          pnpm -v

      - name: Create React manifest
        run: pnpm wally --type "react"

      - name: Install Packages
        run: wally install

      - name: Build
        run: rojo build default.project.json -o test.rbxm

  lint:
    name: Format and Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.3.0

      - name: Format
        run: stylua --check src/

      - name: Lint
        run: selene src/
